[package]
name = "fero"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
lazy_static = "1.5"
arboard = "        3.4.0"
 